# Setting prefix for C-b to C-a
set -g prefix C-a
# Free C-b bindkey
unbind C-b
# Reducing delay in sending commands to editor
set -s escape-time 1
# Setting base index for windows=1. Now C-a 1 will go to first window. Same for panes in a window
set -g base-index 1
setw -g pane-base-index 1

########################
# KEYBINDINGS
########################
# reloading config file
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
# Ensure C-a can be sent to other app. Press C-a TWICE.
bind C-a send-prefix
# Splitting panes. shortcuts made consistent with vim
bind s split-window -v
bind v split-window -h
# moving between panels using prefix + vim motions
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resizing panes by 5 units. '-r' so that prefix may be pressed once for multiple resizes within 500ms(default).
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# enabling vim motions to navigate copy mode. To enter and exit copy mode: prefix+[ and 'Enter' respectively
setw -g mode-keys vi
# vim like bindings to enter copy mode and copy/paste into it
bind Escape copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "xclip -sel clip -i"
unbind p
bind p run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"
